crm/urls.py
from django.conf import settings
from django.conf.urls import url, include
from django.contrib import admin

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^impresario/', include('impresario.urls', namespace='impresario')),
    url(r'^voip/device/', include('voiper.urls.devices', namespace='voiper')),
    url(r'^voip/number/', include('voiper.urls.numbers', namespace='voip_number')),
    url(r'^voip/dhcp/', include('voiper.urls.dhcp', namespace='voip_dhcp')),
    url(r'^voip/context/', include('voiper.urls.context', namespace='voip_context')),
    url(r'^voip/contract/', include('voiper.urls.contracts', namespace='voip_contract')),
    url(r'^voip/asterisk/', include('voiper.urls.asterisk', namespace='voip_asterisk')),
]

if settings.DEBUG:
    import debug_toolbar

    urlpatterns += [
        url(r'^__debug__/', include(debug_toolbar.urls)),
    ]

impresario/urls.py
# -*- coding: UTF-8 -*-
from django.conf.urls import url
from impresario.views import PersonList2, PersonAdd, PersonEdit, PersonList2Json,CustomerList, CustomerAdd, CustomerEdit


app_name = 'impresario'

urlpatterns = [
    # exactly: /impresario/person/
    url(r'^contact/$', PersonList2.as_view(), name='persons_list'),

    url(r'^persons_data/$', PersonList2Json.as_view(), name="persons_list_json"),

    # exactly: /impresario/person/add
    url(r'^contact/add/$', PersonAdd.as_view(), name='persons_add'),

    # example: /impresario/person/1
    url(r'^contact/(?P<pk>\d+)/$', PersonEdit.as_view(), name='persons_edit'),

    # example: /impresario/
    url(r'^$', CustomerList.as_view(), name='customer_list'),

    # exactly: /impresario/add
    url(r'^add/$', CustomerAdd.as_view(), name='customer_add'),

    # example: /impresario/1
    url(r'^(?P<pk>\d+)/$', CustomerEdit.as_view(), name='customer_edit'),

]

impresario/models.py
from django.db import models
from django.core.urlresolvers import reverse


class Person(models.Model):
    """
    Person model.
    """
    first_name = models.CharField('Imię', max_length=32)
    last_name = models.CharField('Nazwisko', max_length=32)

    class Meta:
        app_label = "impresario"
        verbose_name = 'osoba'
        verbose_name_plural = 'osoby'

    def __str__(self):
        return self.last_name + ' ' + self.first_name

    def get_absolute_url(self):
        return reverse("impresario:persons_edit", kwargs={'pk': self.pk})


class Customer(models.Model):
    name = models.CharField(max_length=32)
    contact = models.ManyToManyField(Person)
    sip_proxy = models.GenericIPAddressField('SIP proxy', protocol='IPv4', null=True, blank=True)
    logo_url = models.URLField('Adres URL logo', max_length=100, null=True, blank=True)

    class Meta:
        app_label = "impresario"
        verbose_name = 'klient'
        verbose_name_plural = 'klienci'

    def __str__(self):
        return self.name

    def get_absolute_url(self):
        return reverse("impresario:customer_edit", kwargs={'pk': self.pk})

impresario/forms.py
# -*- coding: UTF-8 -*-
from django import forms
from crispy_forms.helper import FormHelper
from impresario.models import Person, Customer


class PersonCreateForm(forms.ModelForm):

    class Meta:
        model = Person
        fields = [
            'first_name',
            'last_name',
        ]


class CustomerForm(forms.ModelForm):
    helper = FormHelper()
    helper.form_tag = False
    name = forms.CharField(
        label='Nazwa klienta',
        min_length=2,
        max_length=32,
    )
    # sip_proxy = forms.GenericIPAddressField(protocol='IPv4')

    class Meta:
        model = Customer
        fields = [
            'name',
            'contact',
            'sip_proxy',
            'logo_url',
        ]

impresario/views.py
# -*- coding: UTF-8 -*-
from django.views.generic import ListView, CreateView, UpdateView
from impresario.models import Person, Customer
from impresario.forms import PersonCreateForm, CustomerForm
from django.core.urlresolvers import reverse
from django_datatables_view.base_datatable_view import BaseDatatableView


class PersonList(ListView):
    queryset = Person.objects.all()
    model = Person
    template_name = 'persons/list.html'


class PersonList2(ListView):
    queryset = Person.objects.all()
    model = Person
    template_name = 'persons/list2.html'


class PersonList2Json(BaseDatatableView):
    model = Person
    columns = ['last_name', 'first_name']
    order_columns = ['last_name', 'first_name']


class PersonAdd(CreateView):
    model = Person
    template_name = 'persons/form.html'
    form_class = PersonCreateForm

    def get_success_url(self):
        return reverse('impresario:persons_list')


class PersonEdit(UpdateView):
    model = Person
    template_name = 'persons/form.html'
    form_class = PersonCreateForm

    def get_success_url(self):
        return reverse('impresario:persons_list')


class CustomerList(ListView):
    queryset = Customer.objects.all()
    model = Customer
    template_name = 'customers/list.html'


class CustomerAdd(CreateView):
    model = Customer
    form_class = CustomerForm
    template_name = 'customers/form.html'

    def get_success_url(self):
        return reverse('impresario:customer_list')


class CustomerEdit(UpdateView):
    model = Customer
    form_class = CustomerForm
    template_name = 'customers/form.html'

    def get_success_url(self):
        return reverse('impresario:customer_list')

impresario/templates/persons/form.html
{% extends "base.html" %}

{% block title %}{{ block.super }} - Impresario{% endblock %}

{% block content %}
<ol class="breadcrumb">
  <li><a href="#">CRM</a></li>
  <li><a href="/impresario/contact/">Lista kontaktów</a></li>
  <li class="active">Formularz kontaktu</li>
</ol>

<div class="page-header">
    <h1>Kontakt <small>Formularz</small></h1>
</div>

<form method="post" action="./">
    {% csrf_token %}
    {{ form.as_p }}
    <p><input type="submit" value="Zapisz"></p>
</form>

{% endblock %}

impresario/templates/persons/list.html
{% extends "base.html" %}

{% block title %}{{ block.super }} - Impresario{% endblock %}

{% block content %}

<ol class="breadcrumb">
  <li><a href="#">CRM</a></li>
  <li class="active"><a href="/impresario/contact/">Lista kontaktów</a></li>
</ol>

<div class="page-header">
    <h1>Kontakty <small>Lista</small></h1>
</div>



<p class="lead">Lista kontaktów</p>


<ul>
    {% for person in object_list %}
    <li><a href='{{ person.get_absolute_url }}'>{{ person.first_name }} {{ person.last_name }}</a></li>
    {% endfor %}
</ul>

{% endblock %}

impresario/templates/persons/list2.html
{% extends "base.html" %}
{% load i18n staticfiles %}

{% block title %}{{ block.super }} - Impresario{% endblock %}

{% block extra_head %}
<link rel="stylesheet" type="text/css" href="//cdn.datatables.net/1.10.12/css/jquery.dataTables.css">
{% endblock %}

{% block extra_footer %}
<script type="text/javascript" charset="utf8" src="//cdn.datatables.net/1.10.12/js/jquery.dataTables.js"></script>
<script type="text/javascript" charset="utf8" src="//cdn.datatables.net/jquery.dataTables.1.10.2.js"></script>
<script type="text/javascript" charset="utf8" src="/impresario/static/js/ddv_example_1_10.js"></script>
<script type="text/javascript">
        var USERS_LIST_JSON_URL = '{% url "impresario:persons_list_json" %}';
        // translations for datatables

        var dt_language = {
            "emptyTable":     "{% trans "No data available in table" %}",
            "info":           "{% trans "Showing _START_ to _END_ of _TOTAL_ entries" %}",
            "infoEmpty":      "{% trans "Showing 0 to 0 of 0 entries" %}",
            "infoFiltered":   "{% trans "(filtered from _MAX_ total entries)" %}",
            "infoPostFix":    "",
            "thousands":      ",",
            "lengthMenu":     "{% trans "Show _MENU_ entries" %}",
            "loadingRecords": "{% trans "Loading..." %}",
            "processing":     "{% trans "Processing..." %}",
            "search":         "{% trans "Search:" %}",
            "zeroRecords":    "{% trans "No matching records found" %}",
            "paginate": {
                "first":      "{% trans "First" %}",
                "last":       "{% trans "Last" %}",
                "next":       "{% trans "Next" %}",
                "previous":   "{% trans "Previous" %}"
            },
            "aria": {
                "sortAscending":  "{% trans ": activate to sort column ascending" %}",
                "sortDescending": "{% trans ": activate to sort column descending" %}"
            }
        }

</script>
{% endblock %}


{% block content %}

<ol class="breadcrumb">
    <li><a href="#">CRM</a></li>
    <li class="active"><a href="/impresario/contact/">Lista kontaktów</a></li>
</ol>

<div class="page-header">
    <h2>Kontakty
        <small>Lista</small>
    </h2>
</div>

<table class="datatable stripped">
    <thead>
    <th>{% trans "first_name" %}</th>
    <th>{% trans "last_name" %}</th>
    </thead>
    <tbody>
    </tbody>
</table>

{% endblock %}